### ISSUE TITLE
Úkol 1

### ISSUE THREAD

**Issue by girlonabike** [girlonabike/Python-1-ukoly#1]
https://github.com/girlonabike/Python-1-ukoly/blob/main/ukol-1.py
Jenom ještě zkouším, jestli umím zadat to Issue:-) Dík:-)

**Comment by pmoravkova** [comment]
Ahoj, 
reseni dobre. Akorat sice to neni v zadani, ale rozhodne na to chce myslet pri psani jakehokoliv programu - je vzdy treba osetrit, aby program nespadl, kdyz uzivatel zada spatnou vstupni hodnotu. Vetsinou se prave snazis domyslet, co vse se muze pri tom programu stat a nejak to osetrit, aby uzivatel vedel, co kdyztak udelal spatne. 
Tip:
V podmince staci napsat `if baliky[cislo_baliku]:` , to `== True` je zbytecne a vlastne se tam muze napsat, ale nepise. Podminka se vyhodnocuje je pravda/neni pravda, zde tohle pravda je, i kdyz tam neni vyslovne doplneno == True. Kdybys chtela napsat == False, tak to se pak pise `if not baliky[cislo_baliku]:`
